import { WatchCategory, WatchMovement } from "../types";

export interface StyleMeta {
  category: WatchCategory;
  label: string;
  emoji: string;
  badgeBg: string;
  badgeText: string;
  badgeBorder: string;
  accentGlow: string;
  archetype: string;
  keyTraits: string[];
  description: string;
}

export const STYLE_METADATA: Record<string, StyleMeta> = {
  Dress: {
    category: "Dress",
    label: "Dress Watch",
    emoji: "👔",
    badgeBg: "bg-amber-500/15",
    badgeText: "text-amber-300",
    badgeBorder: "border-amber-500/40",
    accentGlow: "shadow-amber-500/20",
    archetype: "Formal Elegance & Pure Simplicity",
    keyTraits: ["Slim Profile (<10mm)", "Precious Metals / Polished Steel", "Guilloché or Minimalist Dial", "Leather or Fine Mesh Strap"],
    description: "Designed to slide effortlessly beneath a tailored shirt cuff. Characterized by clean indices, understated dials, refined proportions, and exquisite hand finishing.",
  },
  Diver: {
    category: "Diver",
    label: "Diver / Maritime",
    emoji: "🌊",
    badgeBg: "bg-cyan-500/15",
    badgeText: "text-cyan-300",
    badgeBorder: "border-cyan-500/40",
    accentGlow: "shadow-cyan-500/20",
    archetype: "Aquatic Tool & ISO 6425 Standard",
    keyTraits: ["Unidirectional 60-Min Bezel", "≥200m Water Resistance", "Heavy Super-LumiNova Application", "Screw-Down Crown & Caseback"],
    description: "Engineered to withstand deep ocean pressures and extreme environments. Features high-contrast luminescence and a rotating elapsed-time timing bezel.",
  },
  Chronograph: {
    category: "Chronograph",
    label: "Chronograph / Motorsport",
    emoji: "🏎️",
    badgeBg: "bg-rose-500/15",
    badgeText: "text-rose-300",
    badgeBorder: "border-rose-500/40",
    accentGlow: "shadow-rose-500/20",
    archetype: "High-Precision Elapsed Timer",
    keyTraits: ["Dual/Triple Sub-Dials", "Tachymeter Scale", "Column-Wheel / Cam Actuation", "Twin Pushers at 2 & 4"],
    description: "The ultimate stopwatch wrist instrument. Designed for calculating speed, distance, and precision elapsed intervals across racing circuits, aviation, and space exploration.",
  },
  Integrated: {
    category: "Integrated",
    label: "Integrated Sports Watch",
    emoji: "⚙️",
    badgeBg: "bg-slate-500/20",
    badgeText: "text-slate-200",
    badgeBorder: "border-slate-400/40",
    accentGlow: "shadow-slate-400/20",
    archetype: "Gérald Genta Geometric Architecture",
    keyTraits: ["Seamless Case-to-Bracelet Flow", "Geometric / Octagonal Bezel", "Intricate Tapisserie Dial Finishing", "Luxury Steel Finishing"],
    description: "Pioneered in the 1970s by Gérald Genta, blending rugged steel durability with haute horlogerie finishing, angular architectural bezels, and seamless taper bracelets.",
  },
  "GMT / Travel": {
    category: "GMT / Travel",
    label: "GMT / Worldtimer",
    emoji: "✈️",
    badgeBg: "bg-blue-500/15",
    badgeText: "text-blue-300",
    badgeBorder: "border-blue-500/40",
    accentGlow: "shadow-blue-500/20",
    archetype: "Dual-Timezone Aviator & Global Instrument",
    keyTraits: ["24-Hour Bidirectional Bezel", "Independent 4th GMT Hand", "Split-Color Day/Night Bezel", "Local-Hour Jumping Setting"],
    description: "Born for transcontinental jet pilots and international travelers to track home and local time simultaneously across timezones.",
  },
  "GMT/Travel": {
    category: "GMT / Travel",
    label: "GMT / Travel Timepiece",
    emoji: "✈️",
    badgeBg: "bg-blue-500/15",
    badgeText: "text-blue-300",
    badgeBorder: "border-blue-500/40",
    accentGlow: "shadow-blue-500/20",
    archetype: "Dual-Timezone Aviator & Global Instrument",
    keyTraits: ["24-Hour Bidirectional Bezel", "Independent 4th GMT Hand", "Split-Color Day/Night Bezel", "Local-Hour Jumping Setting"],
    description: "Born for transcontinental jet pilots and international travelers to track home and local time simultaneously across timezones.",
  },
  "Grand Complication": {
    category: "Grand Complication",
    label: "Grand Complication",
    emoji: "🌌",
    badgeBg: "bg-purple-500/15",
    badgeText: "text-purple-300",
    badgeBorder: "border-purple-500/40",
    accentGlow: "shadow-purple-500/20",
    archetype: "Summit of Astronomical & Micromechanical Art",
    keyTraits: ["Perpetual Calendar / Moonphase", "Tourbillon / Minute Repeater", "Decentralized Dial Architecture", "Hand-Finished Caliber Decoration"],
    description: "The zenith of the watchmaker's art. Incorporates multiple complex astronomical, acoustic, or mechanical complications with hundreds of hand-decorated components.",
  },
  Field: {
    category: "Field",
    label: "Field & Tactical",
    emoji: "🧭",
    badgeBg: "bg-emerald-500/15",
    badgeText: "text-emerald-300",
    badgeBorder: "border-emerald-500/40",
    accentGlow: "shadow-emerald-500/20",
    archetype: "Military Utility & High Legibility",
    keyTraits: ["24-Hour Inner Military Scale", "Matte Anti-Reflective Case", "Durable NATO / Canvas Strap", "Shock-Resistant Movement"],
    description: "Rooted in military heritage, prioritizing instantaneous readability in the field, rugged scratch-resistant finishes, and no-glare matte dials.",
  },
  Pilot: {
    category: "Pilot",
    label: "Pilot / Aviation",
    emoji: "🛩️",
    badgeBg: "bg-amber-500/15",
    badgeText: "text-amber-200",
    badgeBorder: "border-amber-500/30",
    accentGlow: "shadow-amber-500/20",
    archetype: "High-Altitude Flight Instrument",
    keyTraits: ["Oversized Onion Crown", "Flieger Type A/B Dial", "Soft-Iron Anti-Magnetic Cage", "High-Contrast Sword Hands"],
    description: "Designed for aviators needing instantaneous legibility in cockpits, gloved operation via enlarged crowns, and magnetic field resistance.",
  },
  Skeleton: {
    category: "Skeleton",
    label: "Skeleton / Openworked",
    emoji: "💀",
    badgeBg: "bg-violet-500/15",
    badgeText: "text-violet-300",
    badgeBorder: "border-violet-500/40",
    accentGlow: "shadow-violet-500/20",
    archetype: "Architectural Micromechanics & Open Geartrains",
    keyTraits: ["Cutaway Dial & Bridges", "Visible Balance Wheel Oscillation", "Hand Chamfered Angles", "Exhibition Sapphire Front & Back"],
    description: "Reveals the inner beating heart of the movement by paring away non-essential bridge metal to create an intricate kinetic sculpture.",
  },
  Sport: {
    category: "Sport",
    label: "Sport / All-Terrain",
    emoji: "🏅",
    badgeBg: "bg-emerald-500/15",
    badgeText: "text-emerald-300",
    badgeBorder: "border-emerald-500/40",
    accentGlow: "shadow-emerald-500/20",
    archetype: "Rugged Endurance & Dynamic Ergonomics",
    keyTraits: ["Shock-Resistant Casing", "Reinforced Gaskets & Crown Guards", "High-Legibility High-Contrast Markers", "Resilient Steel or Polymer Architecture"],
    description: "Built for active dynamic lifestyle, heavy impacts, sports activities, and everyday resilience.",
  },
  "Vintage Swiss": {
    category: "Vintage Swiss",
    label: "Vintage Swiss Classic",
    emoji: "🕰️",
    badgeBg: "bg-amber-600/15",
    badgeText: "text-amber-300",
    badgeBorder: "border-amber-600/40",
    accentGlow: "shadow-amber-600/20",
    archetype: "Mid-Century Heritage & Timeless Manufacture",
    keyTraits: ["Classic 34–38mm Proportions", "Drilled Lugs & Domed Acrylic Crystal", "Warm Patina / Aged Tritium Aesthetics", "Historic Caliber Architecture"],
    description: "Celebrates the golden era of Swiss mechanical horology from the 1940s through 1970s with timeless charm and enduring collectibility.",
  },
  Occasion: {
    category: "Occasion",
    label: "Special Occasion & Celebration",
    emoji: "✨",
    badgeBg: "bg-yellow-500/15",
    badgeText: "text-yellow-300",
    badgeBorder: "border-yellow-500/40",
    accentGlow: "shadow-yellow-500/20",
    archetype: "Milestone Celebration & Statement Horology",
    keyTraits: ["Precious Accents & Distinctive Finishing", "Refined Dial Artistry", "High Visual Presence", "Commemorative Quality"],
    description: "Curated for weddings, gala galas, milestone anniversaries, and unforgettable celebrations that demand extraordinary refinement.",
  },
  Racing: {
    category: "Racing",
    label: "Racing / Motorsport",
    emoji: "🏎️",
    badgeBg: "bg-red-500/15",
    badgeText: "text-red-400",
    badgeBorder: "border-red-500/40",
    accentGlow: "shadow-red-500/20",
    archetype: "High-Octane Trackside Speed & Lap Timing",
    keyTraits: ["Tachymeter Scale Bezel", "High-Contrast Sub-Dials", "Rally Perforated Strap", "Pusher Ergonomics"],
    description: "Born in the paddock of Monza, Le Mans, and Daytona for precision speed measurement and high-octane motorsport timing.",
  },
  Microbrand: {
    category: "Microbrand",
    label: "Independent Microbrand",
    emoji: "🔬",
    badgeBg: "bg-cyan-500/15",
    badgeText: "text-cyan-300",
    badgeBorder: "border-cyan-500/40",
    accentGlow: "shadow-cyan-500/20",
    archetype: "Enthusiast-Driven Innovation & Pure Value",
    keyTraits: ["Direct-to-Consumer Value Ratio", "Innovative Material Finishing", "Enthusiast-Designed Proportions", "Limited Batch Production"],
    description: "Forward-thinking boutique watchmakers challenging traditional luxury houses with obsessively detailed specifications and direct enthusiast engagement.",
  },
  Minimalist: {
    category: "Minimalist",
    label: "Minimalist / Bauhaus",
    emoji: "📐",
    badgeBg: "bg-zinc-500/15",
    badgeText: "text-zinc-300",
    badgeBorder: "border-zinc-500/40",
    accentGlow: "shadow-zinc-500/20",
    archetype: "Form Follows Function & Pure Modernism",
    keyTraits: ["Clean Geometric Typography", "Spacious Uncluttered Dials", "Slim Straight Wire Lugs", "Understated Neutral Finishes"],
    description: "Rooted in the German Bauhaus and modern industrial design movements where every redundant line is eliminated in pursuit of essential clarity.",
  },
  "Minimalist / Bauhaus": {
    category: "Minimalist / Bauhaus",
    label: "Minimalist / Bauhaus",
    emoji: "📐",
    badgeBg: "bg-zinc-500/15",
    badgeText: "text-zinc-300",
    badgeBorder: "border-zinc-500/40",
    accentGlow: "shadow-zinc-500/20",
    archetype: "Form Follows Function & Pure Modernism",
    keyTraits: ["Clean Geometric Typography", "Spacious Uncluttered Dials", "Slim Straight Wire Lugs", "Understated Neutral Finishes"],
    description: "Rooted in the German Bauhaus and modern industrial design movements where every redundant line is eliminated in pursuit of essential clarity.",
  },
  Moonphase: {
    category: "Moonphase",
    label: "Moonphase / Celestial",
    emoji: "🌙",
    badgeBg: "bg-indigo-500/15",
    badgeText: "text-indigo-300",
    badgeBorder: "border-indigo-500/40",
    accentGlow: "shadow-indigo-500/20",
    archetype: "Celestial Tracking & Astronomical Romance",
    keyTraits: ["29.5-Day Lunar Cycle Aperture", "Gold / Star Sprinkled Disc", "Classic Dial Balancing", "Poetic Mechanical Wonder"],
    description: "Tracks the waxing and waning phases of the lunar cycle on the wrist, connecting wearer to celestial mechanics and ancient calendar traditions.",
  },
  Worldtimer: {
    category: "Worldtimer",
    label: "Worldtimer / Global Master",
    emoji: "🌐",
    badgeBg: "bg-teal-500/15",
    badgeText: "text-teal-300",
    badgeBorder: "border-teal-500/40",
    accentGlow: "shadow-teal-500/20",
    archetype: "Simultaneous 24 Global City Reference",
    keyTraits: ["Outer 24 City Ring", "24-Hour Rotating Disc", "Quickset Push-Button City Jump", "Map / Continents Dial Art"],
    description: "Enables instant readout of time across all 24 major global time zones simultaneously with a single glance at the dial.",
  },
  "Tank / Rectangular": {
    category: "Tank / Rectangular",
    label: "Tank & Rectangular Art Deco",
    emoji: "🏛️",
    badgeBg: "bg-amber-400/15",
    badgeText: "text-amber-200",
    badgeBorder: "border-amber-400/40",
    accentGlow: "shadow-amber-400/20",
    archetype: "Art Deco Geometry & Architectural Distinction",
    keyTraits: ["Parallel Vertical Brancards", "Roman Numeral Dial / Rail Track", "Blue Steel Hands & Crown Cabochon", "Refined Geometric Wrist Presence"],
    description: "Inspired by Louis Cartier's 1917 masterpiece and Art Deco architectural symmetry, presenting a bold non-round silhouette of pure distinction.",
  },
  Everyday: {
    category: "Everyday",
    label: "Everyday / GADA",
    emoji: "⌚",
    badgeBg: "bg-neutral-800/80",
    badgeText: "text-neutral-200",
    badgeBorder: "border-neutral-700/60",
    accentGlow: "shadow-neutral-500/10",
    archetype: "Go-Anywhere-Do-Anything Versatility",
    keyTraits: ["100m Water Resistance", "Balanced 38-41mm Case", "Versatile Bracelet or Strap", "Clean Three-Hand with Date"],
    description: "A balanced timepiece equally comfortable in boardrooms, casual weekend outings, or active sports without skipping a beat.",
  },
};

export function getStyleMetadata(category: string): StyleMeta {
  if (STYLE_METADATA[category]) {
    return STYLE_METADATA[category];
  }
  // Try case-insensitive / partial match
  const foundKey = Object.keys(STYLE_METADATA).find((k) =>
    k.toLowerCase().includes(category.toLowerCase()) || category.toLowerCase().includes(k.toLowerCase())
  );
  if (foundKey && STYLE_METADATA[foundKey]) {
    return STYLE_METADATA[foundKey];
  }
  return {
    category: "Everyday",
    label: category,
    emoji: "⌚",
    badgeBg: "bg-neutral-800/80",
    badgeText: "text-neutral-200",
    badgeBorder: "border-neutral-700/60",
    accentGlow: "shadow-neutral-500/10",
    archetype: "Timepiece Craftsmanship",
    keyTraits: ["Precision Horology", "Refined Proportions", "Curated Reference"],
    description: "A finely crafted horological creation reflecting rich watchmaking heritage and mechanical distinction.",
  };
}

export interface MovementMeta {
  type: WatchMovement["type"];
  label: string;
  iconSymbol: string;
  badgeBg: string;
  badgeText: string;
  badgeBorder: string;
  mechanics: string;
  vphExplanation: string;
  powerReserveNote: string;
  keyBenefits: string[];
}

export const MOVEMENT_METADATA: Record<WatchMovement["type"], MovementMeta> = {
  Automatic: {
    type: "Automatic",
    label: "Automatic (Self-Winding)",
    iconSymbol: "⚡",
    badgeBg: "bg-emerald-500/15",
    badgeText: "text-emerald-300",
    badgeBorder: "border-emerald-500/40",
    mechanics: "Uses a weighted oscillating rotor that rotates freely with natural wrist movement to continuously wind the mainspring barrel.",
    vphExplanation: "Typically oscillates at 28,800 vph (4 Hz), yielding 8 micro-ticks per second for a smooth sweeping second hand.",
    powerReserveNote: "Stays fully wound on the wrist; automatically stores 40–80 hours of kinetic energy when idle.",
    keyBenefits: ["Never needs battery replacement", "Continuous self-winding on wrist", "Smooth mechanical sweep"],
  },
  "Manual Wind": {
    type: "Manual Wind",
    label: "Manual Wind (Hand-Wound)",
    iconSymbol: "🖐️",
    badgeBg: "bg-amber-500/15",
    badgeText: "text-amber-300",
    badgeBorder: "border-amber-500/40",
    mechanics: "Powered entirely by manually winding the crown to tension the mainspring barrel. Unobstructed view of bridges and balance wheel through caseback.",
    vphExplanation: "Traditional classic cadence (typically 18,000–21,600 vph), offering a distinct rhythmic horological tick.",
    powerReserveNote: "Offers 48–8 days of power depending on mainspring barrel architecture.",
    keyBenefits: ["Direct tactile ritual with timepiece", "Ultra-thin case profile (no rotor thickness)", "Unobstructed exhibition caseback view"],
  },
  "Co-Axial": {
    type: "Co-Axial",
    label: "Co-Axial Master Chronometer",
    iconSymbol: "🌀",
    badgeBg: "bg-sky-500/15",
    badgeText: "text-sky-300",
    badgeBorder: "border-sky-500/40",
    mechanics: "Invented by master watchmaker George Daniels, utilizing radial friction rather than sliding friction on escapement pallets to reduce wear.",
    vphExplanation: "Oscillates at 25,200 vph (3.5 Hz), optimized for stability and long-term chronometric precision.",
    powerReserveNote: "Features dual silicon barrels and extreme anti-magnetism (>15,000 Gauss).",
    keyBenefits: ["Radically reduced friction and oil breakdown", "Extended service intervals (8–10 years)", "Resistant to powerful magnetic fields"],
  },
  "Spring Drive": {
    type: "Spring Drive",
    label: "Spring Drive (Continuous Glide)",
    iconSymbol: "🌊",
    badgeBg: "bg-blue-500/15",
    badgeText: "text-blue-300",
    badgeBorder: "border-blue-500/40",
    mechanics: "Mechanical mainspring barrel drives a glide wheel governed by an electromagnetic brake and quartz crystal tri-synchro regulator.",
    vphExplanation: "Zero ticks. The second hand moves in a completely unbroken, silent, fluid continuous glide.",
    powerReserveNote: "Stores 72–120 hours of power reserve with ±1 sec/day chronometric accuracy.",
    keyBenefits: ["True continuous glide motion", "Quartz-level precision with mechanical soul", "Silent, poetic engineering"],
  },
  Tourbillon: {
    type: "Tourbillon",
    label: "Tourbillon Escapement",
    iconSymbol: "💎",
    badgeBg: "bg-purple-500/15",
    badgeText: "text-purple-300",
    badgeBorder: "border-purple-500/40",
    mechanics: "Invented by Abraham-Louis Breguet in 1801; houses the balance wheel and escapement inside a continuously rotating cage (1 revolution per minute) to counteract gravity.",
    vphExplanation: "Micro-engineered cage composed of over 70 ultra-lightweight components weighing less than half a gram.",
    powerReserveNote: "Pinnacle of haute horlogerie mechanical complexity.",
    keyBenefits: ["Gravitational error cancellation", "Hypnotic visual mechanical animation", "Exceptional prestige and artisan craftsmanship"],
  },
  Quartz: {
    type: "Quartz",
    label: "Precision Quartz Oscillator",
    iconSymbol: "🔋",
    badgeBg: "bg-slate-500/15",
    badgeText: "text-slate-300",
    badgeBorder: "border-slate-500/40",
    mechanics: "Battery-powered electronic circuit vibrating a synthetic quartz tuning fork at 32,768 Hz to drive an electric stepping motor.",
    vphExplanation: "Steps exactly once per second (1 Hz) for instantaneous second counting.",
    powerReserveNote: "Battery lifespan typically 2–5 years.",
    keyBenefits: ["Extreme accuracy (±15 sec/month)", "Shock resistance and grab-and-go reliability", "Low maintenance"],
  },
};
